name: peterstoyanov.com
favicon: null
layout_spectrum: 1
typography_spectrum: 0.63531
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5d5d5d'
    - '#000000'
    - '#ffffff'
    - '#ababab'
    - '#272727'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
